In [170]:
import requests
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import re 
import time 
from bs4 import BeautifulSoup

In [64]:
Url='https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops'

In [65]:
requests.get(Url)

In [66]:
page=requests.get(Url)

In [67]:
page.text

'<!doctype html><html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.066267.css"/> <meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><link rel="shortcut icon" href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png"/><meta name="twitter:card" content="app"><meta name="twitter:site" content="@flipkart"><meta name="twitter:creator" content="@flipkart"><meta name="twitter:title" content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com"><meta name="twitter:description" content="Shop for electronics, apparels & more using our Flipkart app Free shipping & COD."><meta name="twitter:app:country" content="in"><meta name="al:ios:app_name" content="Flipkart"><meta name="al:ios:app_store_id" content="742044692"><meta name="twitter:app:name:iphone" content="Flipkart"><meta name="twitter:app:id:iphone" content="742044692"><meta name="twitter:app:url:iphone" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:ipad" content="Flipkart"><meta name="twitter:app:id:ipad" content="742044692"><meta name="twitter:app:url:ipad" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:googleplay" content="Flipkart"><meta name="twitter:app:id:googleplay" content="com.flipkart.android"><meta name="twitter:app:url:googleplay" content="http://dl.flipkart.com/dl/home?"><style>#container {\n\t\t\theight: 100%;\n\t\t}</style>  <link cust-ref-preload-css="preload-css-custom-option" rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css"/> <title>Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta name="og_title" property="og:title" content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com"/><meta name="Keywords" content="Laptops"/> <meta name="Description" content="Laptops- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/><meta property="og:description" content="Laptops- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/>       <meta name="msvalidate.01" content="F4EEB3A0AFFDD385992A06E6920C0AC3"/> <!--[if IE 9 ]>\n\t<script nonce="2348703877327594115">\n\t\twindow.browserVersion = \'IE9\';\n\t\tdocument.documentElement.className += \' ie9\';\n\t</script>\n\t<![endif]--><!--[if !IE]><!--><script nonce="2348703877327594115">if (/*@cc_on!@*/false) {\n\t\t\twindow.browserVersion = \'IE10\';\n\t\t\tdocument.documentElement.className += \' ie10\';\n\t\t}</script><!--<![endif]-->   <link href="https://www.flipkart.com/search?q&#x3D;laptops&amp;sid&#x3D;6bo%2Cb5g&amp;as&#x3D;on&amp;as-show&#x3D;on&amp;otracker&#x3D;AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&amp;otracker1&#x3D;AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&amp;as-pos&#x3D;1&amp;as-type&#x3D;HISTORY&amp;suggestionId&#x3D;laptops%7CLaptops&amp;requestId&#x3D;a66546a4-1232-4fc5-858b-8e3064926b0b&amp;as-searchtext&#x3D;Laptops&amp;page&#x3D;2" id="next-page-link-tag" rel="next"><script nonce="2348703877327594115">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();\n\n\t\tif (requestAnimationFrame && performance && performance.mark) {\n\t\t\trequestAnimationFrame(function () {\n\t\t\t\twindow.first_paint = performance.now();\n\t\t\t\tperformance.mark("first_paint");\n\t\t\t});\n\t\t}\n\n        // web-vitals polyfill for FID\n        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="2348703877327594115">window.dataLayer = window.dataLayer || [];\n\t\tfunction gtag(){dataLayer.push(arguments)};\n\t\tgtag(\'js\', new Date());\n\n\t\tconst pageUri = window.location.pathname;\n    \t\tif (pageUri && pageUri.includes(\'/travel\')) {\n\t\t\tgtag(\'config\', \'AW-16596706887\');\n\t\t}</script></head><body><div id="container"><div><div class="krHvwW"><div class="J+HqMZ"><div class="LOe-Xr"></div><div class="Ja1j8k"><div class="ngOQ7L"><div class="F9+fd2"><a href="/"><img width="75" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png" alt="Flipkart" title="Flipkart" class="W5mR4e"/></a><a class="MwbhDR" href="/plus">Explore<!-- --> <span class="s4NJ5L">Plus</span><img width="10" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/plus_aef861.png"/></a></div></div><div class="kRd8Cs"><form class="Hy6F9O header-form-search" action="/search" method="GET"><div class="col-12-12 BnmXvV"><div class="MoPwtI"><input class="zDPmFV" type="text" title="Search for products, brands and more" name="q" autoComplete="off" placeholder="Search for products, brands and more" value="laptops"/></div><button class="MJG8Up" type="submit"><svg width="20" height="20" viewBox="0 0 17 18" class="" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="EwE-Fa" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="EwE-Fa" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg></button><input type="hidden" name="otracker" value="search"/><input type="hidden" name="otracker1" value="search"/><input type="hidden" name="marketplace" value="FLIPKART"/><input type="hidden" name="as-show" value="off"/><input type="hidden" name="as" value="off"/></div><ul class="col-12-12 bbjHWC"></ul></form></div><div class="RbF1Du UB4mMK"><div class="UL9nZx"><div class="tP+nZg _2E9UgX"><div><a class="wsejfv" href="/account/login?ret=/search%3Fq%3Dlaptops%26sid%3D6bo%252Cb5g%26as%3Don%26as-show%3Don%26otracker%3DAS_QueryStore_HistoryAutoSuggest_1_7_na_na_na%26otracker1%3DAS_QueryStore_HistoryAutoSuggest_1_7_na_na_na%26as-pos%3D1%26as-type%3DHISTORY%26suggestionId%3Dlaptops%257CLaptops%26requestId%3Da66546a4-1232-4fc5-858b-8e3064926b0b%26as-searchtext%3DLaptops">Login</a></div></div></div></div><div class="RbF1Du"><a href="https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect" class="CDJO0-"><span>Become a Seller</span></a></div><div class="RbF1Du"><div class="UL9nZx"><div class="tP+nZg _2E9UgX"><div><div class="_3ZeUN+"> <!-- -->More<!-- --> </div></div></div><svg width="4.7" height="8" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="Wto0b0"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="-dC5Le"></path></svg></div></div><div class="RbF1Du"><div class="tP+nZg"><div class="cjMG1q"><a class="_9Wy27C" href="/viewcart?exploreMode=true&amp;preference=FLIPKART"><svg class="GAbRIN" width="14" height="14" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path class="cziJ98" d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86" fill="#fff"></path></svg><span>Cart</span></a></div></div></div></div><div class="LOe-Xr"></div></div><div class="DlQjC4"></div></div><div class="_5M58Mb"></div><div class="nt6sNV JxFEK3 _48O0EI"><div class="DOjaWF YJG4Cf"><div class="DOjaWF gdgoEp col-2-12" style="flex:0 0 280px;max-width:280px;padding:0px 10px 0px 0px"><div class="DOjaWF gdgoEp col-12-12"><div class="cPHDOP col-12-12"><div class="_0BvurA"><section class="pgRLLn _2OLUF3"><div class="_3Owiq+"><div class="rgHxCQ"><span>Filters</span></div></div></section><div class="GSeM5C"><section class="Iu4qXa"><div class="WCyB2K"><span>CATEGORIES</span></div><div><div class="esFpML"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="IZmjtf"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="P3pAQJ"></path></svg></span><a class="k17cBJ WyLc0s" title="Computers" href="/computers/pr?sid=6bo&amp;q=laptops&amp;otracker=categorytree">Computers</a></div></div><div><div class="esFpML"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="IZmjtf"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class=""></path></svg></span><a class="hEjLuS WyLc0s" title="Laptops" href="/laptops/pr?sid=6bo,b5g&amp;q=laptops&amp;otracker=categorytree">Laptops</a></div></div></section></div><section class="FR+9+z _2OLUF3"><div class="WNK7UT _3Owiq+"><div class="RCE7R3 rgHxCQ"><span>Price</span></div></div><div class="rkYFq7"><div class="gFZVDw"><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div></div></div><div class="-suZGK"><div class="Oyj7AF"><div class="iToJ4v Kaqq1s"><div class="PYKUdo"></div></div><div class="iToJ4v D0puJn"><div class="PYKUdo"></div></div><div class="hZmZbn"></div><div class="hZmZbn AQNm5W"></div></div><div class="C+PahU"><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:0px">.</div></div></div><div class="BXgIa-"><div class="suthUA"><select class="Gn+jFg"><option value="Min" class="_0vP2OD" selected="">Min</option><option value="20000" class="_0vP2OD">₹20000</option><option value="40000" class="_0vP2OD">₹40000</option><option value="50000" class="_0vP2OD">₹50000</option><option value="60000" class="_0vP2OD">₹60000</option><option value="75000" class="_0vP2OD">₹75000</option></select></div><div class="mhoEL5">to</div><div class="tKgS7w"><select class="Gn+jFg"><option value="20000" class="_0vP2OD">₹20000</option><option value="40000" class="_0vP2OD">₹40000</option><option value="50000" class="_0vP2OD">₹50000</option><option value="60000" class="_0vP2OD">₹60000</option><option value="75000" class="_0vP2OD">₹75000</option><option value="Max" class="_0vP2OD" selected="">₹75000+</option></select></div></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Brand</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Type</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Processor</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP rZzKt4"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div><div class="SDsN9S"><div class="bs1+1t"><div class="Cj5b5T"><svg width="20" height="20" viewBox="0 0 17 18" class="zmbstL" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="JVQyl9" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="JVQyl9" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg><input type="text" class="XPD6hh" placeholder="Search Processor" value=""/></div><div class="ewzVkT _3DvUAf" title="Core i5"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i5</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i3"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i3</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i7"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i7</div></label></div></div><div class="ewzVkT _3DvUAf" title="Ryzen 7 Quad Core"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Ryzen 7 Quad Core</div></label></div></div><div class="ewzVkT _3DvUAf" title="Ryzen 5 Quad Core"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Ryzen 5 Quad Core</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i9"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i9</div></label></div></div></div><div class="e+xvXX KvHRYS"><span>56 MORE</span></div></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Processor Generation</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">RAM Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">SSD Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Screen Size</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Operating System</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Weight</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Touch Screen</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Processor Brand</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Usage</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Dedicated Graphics Memory</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Features</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Storage Type</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div c

In [68]:
pagecontent=page.text

In [69]:
soup=BeautifulSoup(pagecontent)

In [70]:
soup

<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.066267.css" rel="stylesheet"/> <meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <link cust-ref-preload-css="preload-css-custom-option" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css" rel="stylesheet"/> <title>Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"><meta content="Laptops" name="Keywords"> <meta content="Laptops- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"><meta content="Laptops- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"> <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"> <!--[if IE 9 ]>
	<script nonce="2348703877327594115">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="2348703877327594115">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <link href="https://www.flipkart.com/search?q=laptops&amp;sid=6bo%2Cb5g&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&amp;otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&amp;as-pos=1&amp;as-type=HISTORY&amp;suggestionId=laptops%7CLaptops&amp;requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&amp;as-searchtext=Laptops&amp;page=2" id="next-page-link-tag" rel="next"/><script nonce="2348703877327594115">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();

		if (requestAnimationFrame && performance && performance.mark) {
			requestAnimationFrame(function () {
				window.first_paint = performance.now();
				performance.mark("first_paint");
			});
		}

        // web-vitals polyfill for FID
        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="2348703877327594115">window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments)};
		gtag('js', new Date());

		const pageUri = window.location.pathname;
    		if (pageUri && pageUri.includes('/travel')) {
			gtag('config', 'AW-16596706887');

In [71]:
LaptopNames=soup.find_all('div',attrs={'class': 'KzDlHZ'})
LaptopNames

[<div class="KzDlHZ">HP 15 Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Windows 11 Home) 15-fd0576TU / 15-fd0467TU Thin...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i3 13th Gen 1315U - (16 GB/512 GB SSD/Windows 11 Home) P1403CVA-S60938WS...</div>,
 <div class="KzDlHZ">Lenovo 100e Chromebook Gen 4 MediaTek Kompanio 520 - (4 GB/32 GB EMMC Storage/Chrome OS) 82W00004HA Ch...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Celeron Dual Core - (8 GB/512 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 7730U - (16 GB/512 GB SSD/Windows 11 Home) Aspire AS15 - 4...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Core i3 13th Gen 1305U - (8 GB/512 GB SSD/Windows 11 Home) A324-53 Thin and Light ...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Celeron Dual Core N4500 - (8 GB/512 GB SSD/Windows 11 Home) A325-45 Thin and Light...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/256 GB SSD/Windows 11 Home) A324-53 Thin and Light Laptop</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Celeron Dual Core - (8 GB/256 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light ...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home) P1503CVA-S70611W...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) P1403CVA-S60343WS ...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Core i3 13th Gen 1305U - (16 GB/512 GB SSD/Windows 11 Home) A324-53 Thin and Light...</div>,
 <div class="KzDlHZ">Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838 - (8 GB/128 GB EMMC Storage/Chrome OS) Ch...</div>,
 <div class="KzDlHZ">Lenovo 100e Chromebook Gen 4 MediaTek MediaTek Kompanio 528 - (4 GB/64 GB EMMC Storage/Chrome OS) 82W0...</div>,
 <div class="KzDlHZ">ASUS Vivobook S14 (2025) with Office 2024 + M365 Basic*, Metallic Design, H-Series Intel Core i5 13th ...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i7 13th Gen 13620H - (16 GB/512 GB SSD/Windows 11 Home) P1503CVA-S71042W...</div>,
 <div class="KzDlHZ">MOTOROLA Motobook 60 Full Metal OLED (i5 14th Gen) Intel Core 5 (Series 2) 210H - (16 GB/512 GB SSD/Wi...</div>,
 <div class="KzDlHZ">Acer Aspire Lite Intel Core i5 12th Gen 12450H - (16 GB/1 TB SSD/Windows 11 Home) AL15-52H Thin and Li...</div>,
 <div class="KzDlHZ">Acer Aspire 3 Intel Celeron Dual Core N4500 - (8 GB/512 GB SSD/Windows 11 Home) A324-45 Thin and Light...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i7 13th Gen 13620H - (32 GB/512 GB SSD/Windows 11 Home) P1403CVA-S60940W...</div>,
 <div class="KzDlHZ">ASUS Expertbook P1 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) P1503CVA-S70501WS ...</div>,
 <div class="KzDlHZ">ASUS Vivobook S14 (2025) with Office 2024 + M365 Basic*, Metallic Design, H-Series Intel Core i5 13th ...</div>,
 <div class="KzDlHZ">Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (16 GB/512 GB SSD/Windows 11 Home) Aspire AS15-42 Thin an...</div>]

In [72]:
LaptopNames[4]

In [73]:
LaptopNames[4].text

'Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 7730U - (16 GB/512 GB SSD/Windows 11 Home) Aspire AS15 - 4...'

In [74]:
Price=soup.find_all('div',attrs={'class': 'Nx9bqj _4b5DiR'})
Price

[<div class="Nx9bqj _4b5DiR">₹55,990</div>,
 <div class="Nx9bqj _4b5DiR">₹36,490</div>,
 <div class="Nx9bqj _4b5DiR">₹9,999</div>,
 <div class="Nx9bqj _4b5DiR">₹17,990</div>,
 <div class="Nx9bqj _4b5DiR">₹38,990</div>,
 <div class="Nx9bqj _4b5DiR">₹28,990</div>,
 <div class="Nx9bqj _4b5DiR">₹22,990</div>,
 <div class="Nx9bqj _4b5DiR">₹27,990</div>,
 <div class="Nx9bqj _4b5DiR">₹15,990</div>,
 <div class="Nx9bqj _4b5DiR">₹27,990</div>,
 <div class="Nx9bqj _4b5DiR">₹50,990</div>,
 <div class="Nx9bqj _4b5DiR">₹34,490</div>,
 <div class="Nx9bqj _4b5DiR">₹30,990</div>,
 <div class="Nx9bqj _4b5DiR">₹15,999</div>,
 <div class="Nx9bqj _4b5DiR">₹10,999</div>,
 <div class="Nx9bqj _4b5DiR">₹58,990</div>,
 <div class="Nx9bqj _4b5DiR">₹58,990</div>,
 <div class="Nx9bqj _4b5DiR">₹54,990</div>,
 <div class="Nx9bqj _4b5DiR">₹46,990</div>,
 <div class="Nx9bqj _4b5DiR">₹21,990</div>,
 <div class="Nx9bqj _4b5DiR">₹66,990</div>,
 <div class="Nx9bqj _4b5DiR">₹34,490</div>,
 <div class="Nx9bqj _4b5DiR">₹58,990</div>,
 <div class="Nx9bqj _4b5DiR">₹36,990</div>]

In [75]:
Price[6]

In [76]:
Price[6].text

'₹22,990'

In [77]:
Ratings=soup.find_all('div',attrs={'class': 'XQDdHH'})
Ratings

[<div class="XQDdHH">4.1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.8<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.8<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.3<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">5<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.8<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">5<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">5<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Js30Fc Ga3i8K">1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">5<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">5<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH">3.9<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Ga3i8K">4<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="XQDdHH Js30Fc Ga3i8K">1<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>]

In [78]:
Ratings[9]

<div class="XQDdHH">4.2<img class="Rza2QY" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>

In [79]:
Ratings[9].text

'4.2'

In [80]:
Processor=soup.find_all('li',attrs={'class': 'J+igdf'})
Processor

[<li class="J+igdf">Intel Core i5 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR4 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">Microsoft Office H&amp;S Edition 2024</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">MediaTek Kompanio 520 Processor</li>,
 <li class="J+igdf">4 GB LPDDR4X RAM</li>,
 <li class="J+igdf">Chrome Operating System</li>,
 <li class="J+igdf">29.46 cm (11.6 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Celeron Dual Core Processor</li>,
 <li class="J+igdf">8 GB DDR4 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">29.46 cm (11.6 inch) Display</li>,
 <li class="J+igdf">1 Year Warranty</li>,
 <li class="J+igdf">AMD Ryzen 7 Octa Core Processor</li>,
 <li class="J+igdf">16 GB DDR4 RAM</li>,
 <li class="J+igdf">Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">8 GB DDR4 RAM</li>,
 <li class="J+igdf">Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Celeron Dual Core Processor</li>,
 <li class="J+igdf">8 GB LPDDR4X RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">1 Year International Travelers Warranty (ITW)</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">8 GB DDR4 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Home Operating System</li>,
 <li class="J+igdf">256 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">1 Year Warranty</li>,
 <li class="J+igdf">Intel Celeron Dual Core Processor</li>,
 <li class="J+igdf">8 GB DDR4 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Home Operating System</li>,
 <li class="J+igdf">256 GB SSD</li>,
 <li class="J+igdf">29.46 cm (11.6 inch) Display</li>,
 <li class="J+igdf">1 Year Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (12th Gen)</li>,
 <li class="J+igdf">8 GB DDR4 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 Inch) Display</li>,
 <li class="J+igdf">1 Year Domestic Warranty</li>,
 <li class="J+igdf">Intel Core i5 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">8 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR4 RAM</li>,
 <li class="J+igdf">Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">MediaTek MediaTek Kompanio 838 Processor</li>,
 <li class="J+igdf">8 GB LPDDR4X RAM</li>,
 <li class="J+igdf">Chrome Operating System</li>,
 <li class="J+igdf">70.64 cm (27.81 cm) Touchscreen Display</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">MediaTek MediaTek Kompanio 528 Processor</li>,
 <li class="J+igdf">4 GB LPDDR4X RAM</li>,
 <li class="J+igdf">Chrome Operating System</li>,
 <li class="J+igdf">29.46 cm (11.6 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Core i5 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps, McAfee 1 year</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i7 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core 5 (Series 2) Processor</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 Inch) Display</li>,
 <li class="J+igdf">Office Home 2024</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i5 Processor (12th Gen)</li>,
 <li class="J+igdf">16 GB LPDDR5 RAM</li>,
 <li class="J+igdf">64 bit Windows 11 Home Operating System</li>,
 <li class="J+igdf">1 TB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">1 Year Onsite warranty</li>,
 <li class="J+igdf">Intel Celeron Dual Core Processor</li>,
 <li class="J+igdf">8 GB LPDDR4X RAM</li>,
 <li class="J+igdf">Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>,
 <li class="J+igdf">Intel Core i7 Processor (13th Gen)</li>,
 <li class="J+igdf">32 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i3 Processor (13th Gen)</li>,
 <li class="J+igdf">8 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 inch) Display</li>,
 <li class="J+igdf">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">Intel Core i5 Processor (13th Gen)</li>,
 <li class="J+igdf">16 GB DDR5 RAM</li>,
 <li class="J+igdf">Windows 11 Home Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">35.56 cm (14 inch) Display</li>,
 <li class="J+igdf">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps, McAfee 1 year</li>,
 <li class="J+igdf">1 Year Onsite Warranty</li>,
 <li class="J+igdf">AMD Ryzen 5 Hexa Core Processor</li>,
 <li class="J+igdf">16 GB DDR4 RAM</li>,
 <li class="J+igdf">Windows 11 Operating System</li>,
 <li class="J+igdf">512 GB SSD</li>,
 <li class="J+igdf">39.62 cm (15.6 Inch) Display</li>,
 <li class="J+igdf">1 Year Carry-in Warranty</li>]

In [81]:
Processor[0]

In [82]:
Processor[0].text

'Intel Core i5 Processor (13th Gen)'

In [83]:
for x in soup.find_all('div', attrs={'class':'yKfJKb row'}):
    Rating1 = x.find('span',attrs={'class':'Wphh3N'})
    if Rating1 is None:
        print(np.nan)
        print()
    else:
        print(Rating1.text)
        print()

220 Ratings & 10 Reviews

889 Ratings & 94 Reviews

572 Ratings & 51 Reviews

1,938 Ratings & 200 Reviews

801 Ratings & 57 Reviews

2,090 Ratings & 161 Reviews

2,774 Ratings & 219 Reviews

2,090 Ratings & 161 Reviews

1,148 Ratings & 109 Reviews

3,789 Ratings & 290 Reviews

797 Ratings & 76 Reviews

889 Ratings & 94 Reviews

2,090 Ratings & 161 Reviews

182 Ratings & 17 Reviews

338 Ratings & 25 Reviews

140 Ratings & 11 Reviews

221 Ratings & 25 Reviews

349 Ratings & 47 Reviews

1,122 Ratings & 113 Reviews

2,774 Ratings & 219 Reviews

221 Ratings & 25 Reviews

889 Ratings & 94 Reviews

140 Ratings & 11 Reviews

1,884 Ratings & 229 Reviews

In [84]:
for i in range(1,25):
    URL='https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops'.format(i)
    print(URL)

https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops
https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops

In [85]:
LaptopNames = []
Price = []
Ratings = []
Processor = []
Page_num = []
for i in range(1,79):
    print('-------------------------------------------------------------------------------------------------')
    start  = time.time()
    URL='https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&otracker1=AS_QueryStore_HistoryAutoSuggest_1_7_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops%7CLaptops&requestId=a66546a4-1232-4fc5-858b-8e3064926b0b&as-searchtext=Laptops'.format(i)
    page=requests.get(URL)
    pagecontent=page.text
    soup = BeautifulSoup(pagecontent)

    for x in soup.find_all('div',attrs={'class':'yKfJKb row'}):
        LaptopNames1 = x.find('div',attrs={'class':'KzDlHZ'})
        Price1 = x.find('div',attrs={'class':'Nx9bqj _4b5DiR'})
        Rating1 = x.find('span',attrs={'class':'Wphh3N'})
        Processor1 = x.find('li',attrs={'class':'J+igdf'})
        
        if LaptopNames1 is None:
            LaptopNames.append(np.nan)
        else:
            LaptopNames.append(LaptopNames1.text)

        if Price1 is None:
            Price.append(np.nan)
        else:
            Price.append(Price1.text)

        if Rating1 is None:
            Ratings.append(np.nan)   
        else:
            Ratings.append(Rating1.text)

        if Processor1 is None:
            Processor.append(np.nan)
        else:
            Processor.append(Processor1.text)
        Page_num.append(i)
    end = time.time()
    print('Page {} is completed in {} seconds'.format(i,end-start))

-------------------------------------------------------------------------------------------------
Page 1 is completed in 1.4929299354553223 seconds
-------------------------------------------------------------------------------------------------
Page 2 is completed in 1.6048285961151123 seconds
-------------------------------------------------------------------------------------------------
Page 3 is completed in 1.563185453414917 seconds
-------------------------------------------------------------------------------------------------
Page 4 is completed in 1.4561188220977783 seconds
-------------------------------------------------------------------------------------------------
Page 5 is completed in 1.810218334197998 seconds
-------------------------------------------------------------------------------------------------
Page 6 is completed in 1.937075138092041 seconds
-------------------------------------------------------------------------------------------------
Page 7 is completed in 1.5685162544250488 seconds
-------------------------------------------------------------------------------------------------
Page 8 is completed in 1.5749266147613525 seconds
-------------------------------------------------------------------------------------------------
Page 9 is completed in 1.8867547512054443 seconds
-------------------------------------------------------------------------------------------------
Page 10 is completed in 1.8837840557098389 seconds
-------------------------------------------------------------------------------------------------
Page 11 is completed in 1.4776721000671387 seconds
-------------------------------------------------------------------------------------------------
Page 12 is completed in 1.6734366416931152 seconds
-------------------------------------------------------------------------------------------------
Page 13 is completed in 1.6205387115478516 seconds
-------------------------------------------------------------------------------------------------
Page 14 is completed in 1.5059494972229004 seconds
-------------------------------------------------------------------------------------------------
Page 15 is completed in 1.4403090476989746 seconds
-------------------------------------------------------------------------------------------------
Page 16 is completed in 1.4259583950042725 seconds
-------------------------------------------------------------------------------------------------
Page 17 is completed in 1.5966954231262207 seconds
-------------------------------------------------------------------------------------------------
Page 18 is completed in 2.0110392570495605 seconds
-------------------------------------------------------------------------------------------------
Page 19 is completed in 2.2526748180389404 seconds
-------------------------------------------------------------------------------------------------
Page 20 is completed in 1.5071706771850586 seconds
-------------------------------------------------------------------------------------------------
Page 21 is completed in 1.62070631980896 seconds
-------------------------------------------------------------------------------------------------
Page 22 is completed in 1.3681831359863281 seconds
-------------------------------------------------------------------------------------------------
Page 23 is completed in 1.559025526046753 seconds
-------------------------------------------------------------------------------------------------
Page 24 is completed in 1.5730812549591064 seconds
-------------------------------------------------------------------------------------------------
Page 25 is completed in 1.5242669582366943 seconds
-------------------------------------------------------------------------------------------------
Page 26 is completed in 1.8582763671875 seconds
-------------------------------------------------------------------------------------------------
Page 27 is completed in 1.3218481540679932 seconds
-------------------------------------------------------------------------------------------------
Page 28 is completed in 1.4815795421600342 seconds
-------------------------------------------------------------------------------------------------
Page 29 is completed in 1.7878267765045166 seconds
-------------------------------------------------------------------------------------------------
Page 30 is completed in 2.1126222610473633 seconds
-------------------------------------------------------------------------------------------------
Page 31 is completed in 1.4788451194763184 seconds
-------------------------------------------------------------------------------------------------
Page 32 is completed in 1.6264722347259521 seconds
-------------------------------------------------------------------------------------------------
Page 33 is completed in 1.9543178081512451 seconds
-------------------------------------------------------------------------------------------------
Page 34 is completed in 1.3409910202026367 seconds
-------------------------------------------------------------------------------------------------
Page 35 is completed in 1.486504077911377 seconds
-------------------------------------------------------------------------------------------------
Page 36 is completed in 1.652780294418335 seconds
-------------------------------------------------------------------------------------------------
Page 37 is completed in 1.3678619861602783 seconds
-------------------------------------------------------------------------------------------------
Page 38 is completed in 1.45997953414917 seconds
-------------------------------------------------------------------------------------------------
Page 39 is completed in 1.5815351009368896 seconds
-------------------------------------------------------------------------------------------------
Page 40 is completed in 1.7564353942871094 seconds
-------------------------------------------------------------------------------------------------
Page 41 is completed in 1.4476478099822998 seconds
-------------------------------------------------------------------------------------------------
Page 42 is completed in 1.6737499237060547 seconds
-------------------------------------------------------------------------------------------------
Page 43 is completed in 2.3249871730804443 seconds
-------------------------------------------------------------------------------------------------
Page 44 is completed in 0.9377562999725342 seconds
-------------------------------------------------------------------------------------------------
Page 45 is completed in 1.0315351486206055 seconds
-------------------------------------------------------------------------------------------------
Page 46 is completed in 0.2765648365020752 seconds
-------------------------------------------------------------------------------------------------
Page 47 is completed in 0.2676682472229004 seconds
-------------------------------------------------------------------------------------------------
Page 48 is completed in 1.146855115890503 seconds
-------------------------------------------------------------------------------------------------
Page 49 is completed in 1.2040917873382568 seconds
-------------------------------------------------------------------------------------------------
Page 50 is completed in 0.9114327430725098 seconds
-------------------------------------------------------------------------------------------------
Page 51 is completed in 1.0734379291534424 seconds
-------------------------------------------------------------------------------------------------
Page 52 is completed in 0.9151887893676758 seconds
-------------------------------------------------------------------------------------------------
Page 53 is completed in 0.20194053649902344 seconds
-------------------------------------------------------------------------------------------------
Page 54 is completed in 0.8653230667114258 seconds
-------------------------------------------------------------------------------------------------
Page 55 is completed in 0.9573581218719482 seconds
-------------------------------------------------------------------------------------------------
Page 56 is completed in 0.8568325042724609 seconds
-------------------------------------------------------------------------------------------------
Page 57 is completed in 0.9694714546203613 seconds
-------------------------------------------------------------------------------------------------
Page 58 is completed in 1.545497179031372 seconds
-------------------------------------------------------------------------------------------------
Page 59 is completed in 0.867957353591919 seconds
-------------------------------------------------------------------------------------------------
Page 60 is completed in 0.9389181137084961 seconds
-------------------------------------------------------------------------------------------------
Page 61 is completed in 0.9091999530792236 seconds
-------------------------------------------------------------------------------------------------
Page 62 is completed in 0.9147603511810303 seconds
-------------------------------------------------------------------------------------------------
Page 63 is completed in 1.0829858779907227 seconds
-------------------------------------------------------------------------------------------------
Page 64 is completed in 0.27251553535461426 seconds
-------------------------------------------------------------------------------------------------
Page 65 is completed in 1.0481081008911133 seconds
-------------------------------------------------------------------------------------------------
Page 66 is completed in 1.0990419387817383 seconds
-------------------------------------------------------------------------------------------------
Page 67 is completed in 0.8482151031494141 seconds
-------------------------------------------------------------------------------------------------
Page 68 is completed in 0.9886205196380615 seconds
-------------------------------------------------------------------------------------------------
Page 69 is completed in 0.8631000518798828 seconds
-------------------------------------------------------------------------------------------------
Page 70 is completed in 0.8208138942718506 seconds
-------------------------------------------------------------------------------------------------
Page 71 is completed in 1.7190353870391846 seconds
-------------------------------------------------------------------------------------------------
Page 72 is completed in 1.1979029178619385 seconds
-------------------------------------------------------------------------------------------------
Page 73 is completed in 0.9656639099121094 seconds
-------------------------------------------------------------------------------------------------
Page 74 is completed in 1.058408260345459 seconds
-------------------------------------------------------------------------------------------------
Page 75 is completed in 1.24542236328125 seconds
-------------------------------------------------------------------------------------------------
Page 76 is completed in 0.8927297592163086 seconds
-------------------------------------------------------------------------------------------------
Page 77 is completed in 1.029472827911377 seconds
-------------------------------------------------------------------------------------------------
Page 78 is completed in 1.0976471900939941 seconds

In [86]:
len(LaptopNames)

1776

In [87]:
data = {'LaptopNames':LaptopNames,'Price':Price,'Ratings':Ratings,'Processor':Processor,'Page_num':Page_num}
df = pd.DataFrame(data)

In [88]:
df

,LaptopNames,Price,Ratings,Processor,Page_num
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1
...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78

In [91]:
regex=r'\(\d+\sGB\/'
df['RAM']=df['LaptopNames'].apply(lambda x: re.findall(regex,x))

In [92]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,[(4 GB/]
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/]
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,[(16 GB/]
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/]
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,[(8 GB/]
...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,[(8 GB/]
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,[(32 GB/]
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,[(8 GB/]
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[]
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,[(16 GB/]

In [95]:
regex= r'\b\d+(?:\.\d+)?\s*(?:GB|TB)\s*(?:SSD|HDD)\b'
df['Storage']=df['LaptopNames'].apply(lambda x: re.findall(regex,x))

In [96]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,[(4 GB/],[]
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD]
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,[(16 GB/],[512 GB SSD]
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD]
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,[(8 GB/],[256 GB SSD]
...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,[(8 GB/],[512 GB SSD]
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,[(32 GB/],[512 GB SSD]
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,[(8 GB/],[512 GB SSD]
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[]
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,[(16 GB/],[512 GB SSD]

In [97]:
df['LaptopNames'][2]

'Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 7730U - (16 GB/512 GB SSD/Windows 11 Home) Aspire AS15 - 4...'

In [98]:
re.findall(r'^\w+',df['LaptopNames'][2])

['Acer']

In [99]:
regex=r'^\w+'
df['BrandName']=df['LaptopNames'].apply(lambda x: re.findall(regex,x))

In [100]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage,BrandName
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,[(4 GB/],[],[Lenovo]
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD],[Acer]
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,[(16 GB/],[512 GB SSD],[Acer]
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD],[Acer]
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,[(8 GB/],[256 GB SSD],[Acer]
...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,[(8 GB/],[512 GB SSD],[Acer]
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,[(32 GB/],[512 GB SSD],[ASUS]
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,[(8 GB/],[512 GB SSD],[ASUS]
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[],[ASUS]
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,[(16 GB/],[512 GB SSD],[Acer]

In [101]:
df['LaptopNames'][2]

'Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 7730U - (16 GB/512 GB SSD/Windows 11 Home) Aspire AS15 - 4...'

In [102]:
re.findall(r'^(.*?)\s+(?:Intel|AMD|MediaTek)\b',df['LaptopNames'][2])

['Acer Aspire 3 Backlit']

In [103]:
regex=r'^(.*?)\s+(?:Intel|AMD|MediaTek)\b'
df['ModelName']=df['LaptopNames'].apply(lambda x: re.findall(regex,x))

In [104]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage,BrandName,ModelName
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,[(4 GB/],[],[Lenovo],[Lenovo 100e Chromebook Gen 4]
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD],[Acer],[Acer Aspire 3]
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,[(16 GB/],[512 GB SSD],[Acer],[Acer Aspire 3 Backlit]
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,[(8 GB/],[512 GB SSD],[Acer],[Acer Aspire 3]
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,[(8 GB/],[256 GB SSD],[Acer],[Acer Aspire 3]
...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,[(8 GB/],[512 GB SSD],[Acer],[Acer Aspire 3]
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,[(32 GB/],[512 GB SSD],[ASUS],[ASUS Expertbook P1]
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,[(8 GB/],[512 GB SSD],[ASUS],[ASUS Expertbook P1]
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[],[ASUS],[ASUS Vivobook S14 (2025) with Office 2024 + M...
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,[(16 GB/],[512 GB SSD],[Acer],[Acer Aspire 15]

In [105]:
df.to_csv('Laptops_data_30 E.csv')

In [106]:
df=pd.read_csv('Laptops_data_30 E.csv')

In [107]:
df

,Unnamed: 0,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage,BrandName,ModelName
0,0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4']
1,1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
2,2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit']
3,3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
4,4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3']
...,...,...,...,...,...,...,...,...,...,...
1771,1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
1772,1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1']
1773,1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1']
1774,1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...
1775,1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15']

In [108]:
df = pd.read_csv("Laptops_data_30 E.csv")

# Remove 'Unnamed: 0' column if it exists
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])


df.to_csv("Laptops_data_cleaned.csv", index=False)

In [109]:
df=pd.read_csv('Laptops_data_cleaned.csv')

In [110]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage,BrandName,ModelName
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4']
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit']
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3']
...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3']
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1']
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1']
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15']

In [111]:
# Split Ratings and Reviews
df['RatingsCount'] = df['Ratings'].str.extract(r'(\d[\d,]*)').replace(',', '', regex=True).astype(int)
df['ReviewsCount'] = df['Ratings'].str.extract(r'(\d[\d,]*)\s+Ratings.*?(\d[\d,]*)')[1].replace(',', '', regex=True).astype(int)

# Save cleaned file
df.to_csv("Laptops_data_cleaned.csv", index=False)

In [112]:
df

,LaptopNames,Price,Ratings,Processor,Page_num,RAM,Storage,BrandName,ModelName,RatingsCount,ReviewsCount
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",572 Ratings & 51 Reviews,MediaTek Kompanio 520 Processor,1,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4'],572,51
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990","1,938 Ratings & 200 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],1938,200
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",801 Ratings & 57 Reviews,AMD Ryzen 7 Octa Core Processor,1,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit'],801,57
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990","2,090 Ratings & 161 Reviews",Intel Core i3 Processor (13th Gen),1,['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3'],2090,161
...,...,...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990","2,774 Ratings & 219 Reviews",Intel Celeron Dual Core Processor,78,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",221 Ratings & 25 Reviews,Intel Core i7 Processor (13th Gen),78,['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],221,25
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",889 Ratings & 94 Reviews,Intel Core i3 Processor (13th Gen),78,['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],889,94
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",140 Ratings & 11 Reviews,Intel Core i5 Processor (13th Gen),78,[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...,140,11
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990","1,884 Ratings & 229 Reviews",AMD Ryzen 5 Hexa Core Processor,78,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15'],1884,229

In [113]:
#Drop ratings column
df = df.drop(columns=["Ratings"])

# Save again
df.to_csv("Laptops_data_cleaned.csv", index=False)

In [114]:
df=pd.read_csv('Laptops_data_cleaned.csv')

In [115]:
df

,LaptopNames,Price,Processor,Page_num,RAM,Storage,BrandName,ModelName,RatingsCount,ReviewsCount
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",MediaTek Kompanio 520 Processor,1,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4'],572,51
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],1938,200
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",AMD Ryzen 7 Octa Core Processor,1,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit'],801,57
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990",Intel Core i3 Processor (13th Gen),1,['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3'],2090,161
...,...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990",Intel Celeron Dual Core Processor,78,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",Intel Core i7 Processor (13th Gen),78,['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],221,25
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",Intel Core i3 Processor (13th Gen),78,['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],889,94
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",Intel Core i5 Processor (13th Gen),78,[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...,140,11
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990",AMD Ryzen 5 Hexa Core Processor,78,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15'],1884,229

In [120]:
df=pd.read_csv('Laptops_data_cleaned.csv')

In [121]:
df

,LaptopNames,Price,Processor,Page_num,RAM,Storage,BrandName,ModelName,RatingsCount,ReviewsCount
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",MediaTek Kompanio 520 Processor,1,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4'],572,51
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],1938,200
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",AMD Ryzen 7 Octa Core Processor,1,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit'],801,57
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990",Intel Celeron Dual Core Processor,1,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990",Intel Core i3 Processor (13th Gen),1,['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3'],2090,161
...,...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990",Intel Celeron Dual Core Processor,78,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",Intel Core i7 Processor (13th Gen),78,['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],221,25
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",Intel Core i3 Processor (13th Gen),78,['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],889,94
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",Intel Core i5 Processor (13th Gen),78,[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...,140,11
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990",AMD Ryzen 5 Hexa Core Processor,78,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15'],1884,229

In [122]:
#Drop page num
df = df.drop(columns=['Page_num'])
df

,LaptopNames,Price,Processor,RAM,Storage,BrandName,ModelName,RatingsCount,ReviewsCount
0,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹9,999",MediaTek Kompanio 520 Processor,['(4 GB/'],[],['Lenovo'],['Lenovo 100e Chromebook Gen 4'],572,51
1,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],1938,200
2,Acer Aspire 3 Backlit AMD Ryzen 7 Octa Core 77...,"₹38,990",AMD Ryzen 7 Octa Core Processor,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3 Backlit'],801,57
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹22,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
4,Acer Aspire 3 Intel Core i3 13th Gen - (8 GB/2...,"₹27,990",Intel Core i3 Processor (13th Gen),['(8 GB/'],['256 GB SSD'],['Acer'],['Acer Aspire 3'],2090,161
...,...,...,...,...,...,...,...,...,...
1771,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹21,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 3'],2774,219
1772,ASUS Expertbook P1 Intel Core i7 13th Gen 1362...,"₹66,990",Intel Core i7 Processor (13th Gen),['(32 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],221,25
1773,ASUS Expertbook P1 Intel Core i3 13th Gen 1315...,"₹34,490",Intel Core i3 Processor (13th Gen),['(8 GB/'],['512 GB SSD'],['ASUS'],['ASUS Expertbook P1'],889,94
1774,ASUS Vivobook S14 (2025) with Office 2024 + M3...,"₹58,990",Intel Core i5 Processor (13th Gen),[],[],['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...,140,11
1775,Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U - (...,"₹36,990",AMD Ryzen 5 Hexa Core Processor,['(16 GB/'],['512 GB SSD'],['Acer'],['Acer Aspire 15'],1884,229

In [144]:
# Get the list of all columns.
cols = df.columns.tolist()

cols.remove('BrandName')
cols.remove('ModelName')

# Create a new list with the desired order.
new_cols = ['BrandName', 'ModelName'] + cols

# Reorder the DataFrame columns.
df_reordered = df[new_cols]

# Print the first 5 rows and the info of the new DataFrame to confirm the new column order.
print('\nRe-ordered DataFrame head:')
print(df_reordered.head())
print('\nRe-ordered DataFrame info:')
print(df_reordered.info())

# Save the reordered data to a new CSV file.
df_reordered.to_csv('laptops_reordered.csv', index=False)

#Drop LaptopNames
df=df.drop(columns=['LaptopNames'])

Re-ordered DataFrame head:
    BrandName                         ModelName    Price  \
0  ['Lenovo']  ['Lenovo 100e Chromebook Gen 4']   ₹9,999
1    ['Acer']                 ['Acer Aspire 3']  ₹17,990
2    ['Acer']         ['Acer Aspire 3 Backlit']  ₹38,990
3    ['Acer']                 ['Acer Aspire 3']  ₹22,990
4    ['Acer']                 ['Acer Aspire 3']  ₹27,990

                            Processor  Page_num          RAM         Storage  \
0     MediaTek Kompanio 520 Processor         1   ['(4 GB/']              []
1   Intel Celeron Dual Core Processor         1   ['(8 GB/']  ['512 GB SSD']
2     AMD Ryzen 7 Octa Core Processor         1  ['(16 GB/']  ['512 GB SSD']
3   Intel Celeron Dual Core Processor         1   ['(8 GB/']  ['512 GB SSD']
4  Intel Core i3 Processor (13th Gen)         1   ['(8 GB/']  ['256 GB SSD']

   RatingsCount  ReviewsCount
0           572            51
1          1938           200
2           801            57
3          2774           219
4          2090           161

Re-ordered DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   BrandName     1776 non-null   object
 1   ModelName     1776 non-null   object
 2   Price         1776 non-null   object
 3   Processor     1776 non-null   object
 4   Page_num      1776 non-null   int64
 5   RAM           1776 non-null   object
 6   Storage       1776 non-null   object
 7   RatingsCount  1776 non-null   int64
 8   ReviewsCount  1776 non-null   int64
dtypes: int64(3), object(6)
memory usage: 125.0+ KB
None

In [162]:
df.to_csv('Laptop_data_50B.csv', index=False)

In [163]:
df

,BrandName,ModelName,Price,Processor,RAM,Storage,RatingsCount,ReviewsCount
0,['Lenovo'],['Lenovo 100e Chromebook Gen 4'],"₹9,999",MediaTek Kompanio 520 Processor,['(4 GB/'],[],572,51
1,['Acer'],['Acer Aspire 3'],"₹17,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],1938,200
2,['Acer'],['Acer Aspire 3 Backlit'],"₹38,990",AMD Ryzen 7 Octa Core Processor,['(16 GB/'],['512 GB SSD'],801,57
3,['Acer'],['Acer Aspire 3'],"₹22,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],2774,219
4,['Acer'],['Acer Aspire 3'],"₹27,990",Intel Core i3 Processor (13th Gen),['(8 GB/'],['256 GB SSD'],2090,161
...,...,...,...,...,...,...,...,...
1771,['Acer'],['Acer Aspire 3'],"₹21,990",Intel Celeron Dual Core Processor,['(8 GB/'],['512 GB SSD'],2774,219
1772,['ASUS'],['ASUS Expertbook P1'],"₹66,990",Intel Core i7 Processor (13th Gen),['(32 GB/'],['512 GB SSD'],221,25
1773,['ASUS'],['ASUS Expertbook P1'],"₹34,490",Intel Core i3 Processor (13th Gen),['(8 GB/'],['512 GB SSD'],889,94
1774,['ASUS'],['ASUS Vivobook S14 (2025) with Office 2024 + ...,"₹58,990",Intel Core i5 Processor (13th Gen),[],[],140,11
1775,['Acer'],['Acer Aspire 15'],"₹36,990",AMD Ryzen 5 Hexa Core Processor,['(16 GB/'],['512 GB SSD'],1884,229

In [165]:
#How many features(Columns) do you have? 
df = pd.read_csv("Laptop_data_50B.csv")
print("Number of columns:", df.shape[1])
print("Column names:", df.columns.tolist())

Number of columns: 8
Column names: ['BrandName', 'ModelName', 'Price', 'Processor', 'RAM', 'Storage', 'RatingsCount', 'ReviewsCount']

In [166]:
#How many observations(rows) do you have? 
df = pd.read_csv("Laptop_data_50B.csv")
print("Number of rows:", df.shape[0])

Number of rows: 1776

In [167]:
#What is the data type of each feature(Columns)? 
df = pd.read_csv("Laptop_data_50B.csv")
print(df.dtypes)

BrandName       object
ModelName       object
Price           object
Processor       object
RAM             object
Storage         object
RatingsCount     int64
ReviewsCount     int64
dtype: object

In [168]:
#How many missing values are there?
df = pd.read_csv("Laptop_data_50B.csv")
print(df.isnull().sum())

BrandName       0
ModelName       0
Price           0
Processor       0
RAM             0
Storage         0
RatingsCount    0
ReviewsCount    0
dtype: int64

In [181]:
# Load the data from the uploaded CSV file.
df = pd.read_csv("Laptop_data_50B.csv")

###Removing Rupess Symbol
# Clean the 'Price' column: remove '₹' and commas, then convert to numeric
df['Price'] = df['Price'].str.replace('₹', '', regex=True)
df['Price'] = df['Price'].str.replace(',', '', regex=True)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Save the cleaned DataFrame to a new CSV file
df.to_csv("Laptop_data_50B.csv", index=False)

In [182]:
df

,BrandName,ModelName,Price,Processor,RAM,Storage,RatingsCount,ReviewsCount
0,Lenovo,Lenovo 100e Chromebook Gen 4,9999,MediaTek Kompanio 520 Processor,(4 GB/,NaN,572,51
1,Acer,Acer Aspire 3,17990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,1938,200
2,Acer,Acer Aspire 3 Backlit,38990,AMD Ryzen 7 Octa Core Processor,(16 GB/,512 GB SSD,801,57
3,Acer,Acer Aspire 3,22990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,2774,219
4,Acer,Acer Aspire 3,27990,Intel Core i3 Processor (13th Gen),(8 GB/,256 GB SSD,2090,161
...,...,...,...,...,...,...,...,...
1771,Acer,Acer Aspire 3,21990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,2774,219
1772,ASUS,ASUS Expertbook P1,66990,Intel Core i7 Processor (13th Gen),(32 GB/,512 GB SSD,221,25
1773,ASUS,ASUS Expertbook P1,34490,Intel Core i3 Processor (13th Gen),(8 GB/,512 GB SSD,889,94
1774,ASUS,ASUS Vivobook S14 (2025) with Office 2024 + M3...,58990,Intel Core i5 Processor (13th Gen),NaN,NaN,140,11
1775,Acer,Acer Aspire 15,36990,AMD Ryzen 5 Hexa Core Processor,(16 GB/,512 GB SSD,1884,229

In [185]:
df = pd.read_csv("Laptop_data_50B.csv")

# Clean columns with list-like strings
def clean_string_column(series):
    if pd.api.types.is_object_dtype(series):
        series = series.str.replace("\[|\]|\'", "", regex=True)
        return series
    return series

for col in ['BrandName', 'ModelName', 'RAM', 'Storage']:
    df[col] = clean_string_column(df[col])

# Check for missing values in 'RAM' and 'Storage'
print("Missing values before imputation:")
print(df[['RAM', 'Storage']].isnull().sum())

# Find the mode (most frequent value) for 'RAM' and 'Storage'
ram_mode = df['RAM'].mode()[0]
storage_mode = df['Storage'].mode()[0]

print(f"\nMost frequent RAM value (mode): '{ram_mode}'")
print(f"Most frequent Storage value (mode): '{storage_mode}'")

# Impute missing values with the mode
df['RAM'].fillna(ram_mode, inplace=True)
df['Storage'].fillna(storage_mode, inplace=True)

# Check for missing values after imputation
print("\nMissing values after imputation:")
print(df[['RAM', 'Storage']].isnull().sum())

# Save the imputed data to a new CSV file
df.to_csv("Laptop_data_50B.csv", index=False)

Missing values before imputation:
RAM        148
Storage    374
dtype: int64

Most frequent RAM value (mode): '(8 GB/'
Most frequent Storage value (mode): '512 GB SSD'

Missing values after imputation:
RAM        0
Storage    0
dtype: int64

<>:6: SyntaxWarning: invalid escape sequence '\['
<>:6: SyntaxWarning: invalid escape sequence '\['
C:\Users\ASUS\AppData\Local\Temp\ipykernel_11832\2102458896.py:6: SyntaxWarning: invalid escape sequence '\['
  series = series.str.replace("\[|\]|\'", "", regex=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_11832\2102458896.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RAM'].fillna(ram_mode, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_11832\2102458896.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Storage'].fillna(storage_mode, inplace=True)

In [190]:
df=pd.read_csv("Laptop_data_50B.csv")
df

,BrandName,ModelName,Price,Processor,RAM,Storage,RatingsCount,ReviewsCount
0,Lenovo,Lenovo 100e Chromebook Gen 4,9999,MediaTek Kompanio 520 Processor,(4 GB/,512 GB SSD,572,51
1,Acer,Acer Aspire 3,17990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,1938,200
2,Acer,Acer Aspire 3 Backlit,38990,AMD Ryzen 7 Octa Core Processor,(16 GB/,512 GB SSD,801,57
3,Acer,Acer Aspire 3,22990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,2774,219
4,Acer,Acer Aspire 3,27990,Intel Core i3 Processor (13th Gen),(8 GB/,256 GB SSD,2090,161
...,...,...,...,...,...,...,...,...
1771,Acer,Acer Aspire 3,21990,Intel Celeron Dual Core Processor,(8 GB/,512 GB SSD,2774,219
1772,ASUS,ASUS Expertbook P1,66990,Intel Core i7 Processor (13th Gen),(32 GB/,512 GB SSD,221,25
1773,ASUS,ASUS Expertbook P1,34490,Intel Core i3 Processor (13th Gen),(8 GB/,512 GB SSD,889,94
1774,ASUS,ASUS Vivobook S14 (2025) with Office 2024 + M3...,58990,Intel Core i5 Processor (13th Gen),(8 GB/,512 GB SSD,140,11
1775,Acer,Acer Aspire 15,36990,AMD Ryzen 5 Hexa Core Processor,(16 GB/,512 GB SSD,1884,229

In [191]:
df = pd.read_csv('Laptop_data_50B.csv')

# Remove '(' and '/' from the 'RAM' column
df['RAM'] = df['RAM'].str.replace('(', '').str.replace('/', '')

# Display the first 5 rows of the updated DataFrame
print(df.head())

# Save the updated DataFrame to a new CSV file
df.to_csv('Laptop_data_50B.csv', index=False)

  BrandName                     ModelName  Price  \
0    Lenovo  Lenovo 100e Chromebook Gen 4   9999
1      Acer                 Acer Aspire 3  17990
2      Acer         Acer Aspire 3 Backlit  38990
3      Acer                 Acer Aspire 3  22990
4      Acer                 Acer Aspire 3  27990

                            Processor    RAM     Storage  RatingsCount  \
0     MediaTek Kompanio 520 Processor   4 GB  512 GB SSD           572
1   Intel Celeron Dual Core Processor   8 GB  512 GB SSD          1938
2     AMD Ryzen 7 Octa Core Processor  16 GB  512 GB SSD           801
3   Intel Celeron Dual Core Processor   8 GB  512 GB SSD          2774
4  Intel Core i3 Processor (13th Gen)   8 GB  256 GB SSD          2090

   ReviewsCount
0            51
1           200
2            57
3           219
4           161

In [193]:
df=pd.read_csv('Laptop_data_50B.csv')
df

,BrandName,ModelName,Price,Processor,RAM,Storage,RatingsCount,ReviewsCount
0,Lenovo,Lenovo 100e Chromebook Gen 4,9999,MediaTek Kompanio 520 Processor,4 GB,512 GB SSD,572,51
1,Acer,Acer Aspire 3,17990,Intel Celeron Dual Core Processor,8 GB,512 GB SSD,1938,200
2,Acer,Acer Aspire 3 Backlit,38990,AMD Ryzen 7 Octa Core Processor,16 GB,512 GB SSD,801,57
3,Acer,Acer Aspire 3,22990,Intel Celeron Dual Core Processor,8 GB,512 GB SSD,2774,219
4,Acer,Acer Aspire 3,27990,Intel Core i3 Processor (13th Gen),8 GB,256 GB SSD,2090,161
...,...,...,...,...,...,...,...,...
1771,Acer,Acer Aspire 3,21990,Intel Celeron Dual Core Processor,8 GB,512 GB SSD,2774,219
1772,ASUS,ASUS Expertbook P1,66990,Intel Core i7 Processor (13th Gen),32 GB,512 GB SSD,221,25
1773,ASUS,ASUS Expertbook P1,34490,Intel Core i3 Processor (13th Gen),8 GB,512 GB SSD,889,94
1774,ASUS,ASUS Vivobook S14 (2025) with Office 2024 + M3...,58990,Intel Core i5 Processor (13th Gen),8 GB,512 GB SSD,140,11
1775,Acer,Acer Aspire 15,36990,AMD Ryzen 5 Hexa Core Processor,16 GB,512 GB SSD,1884,229